#!/bin/bash

aws cloudformation create-stack --stack-name steveJenkins --template-body file://vpc-only.json --parameters ParameterKey=KeyPair,ParameterValue=steveshilling ParameterKey=subnetAZ,ParameterValue=eu-central-1b ParameterKey=Region,ParameterValue=eu-central-1

