#!/bin/bash

if (( $# < 3 ))
then
	echo "SYNTAX: $0 <TAG> <userdata> <REGION>"
	exit 1
fi
TAG=$1
provfile=$2
REGION=$3

aws ec2 run-instances --image-id ami-06ce3edf0cff21f07 --count 1 --instance-type t2.micro --key-name steveshillingacademyie --security-groups AcademySG --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$TAG}]" "ResourceType=volume,Tags=[{Key=Name,Value=$TAG}]" --user-data file://$provfile --region $REGION
