#!/bin/bash

aws cloudformation create-stack --stack-name steveVM --template-body file://vpc-only.json --parameters ParameterKey=KeyPair,ParameterValue=steveshilling ParameterKey=subnetAZ,ParameterValue=us-east-1b ParameterKey=Region,ParameterValue=us-east-1

