#!/bin/bash

aws cloudformation create-stack --stack-name steveVM-servers --template-body file://vpc-servers.json --parameters ParameterKey=KeyPair,ParameterValue=steveshilling ParameterKey=PubSub,ParameterValue=subnet-aaafc8d0 ParameterKey=PrivSub,ParameterValue=subnet-58afc822 ParameterKey=VpcCidr,ParameterValue=10.0.0.0/24  ParameterKey=VpcId,ParameterValue=vpc-9bef70f3

