#!/bin/bash

aws cloudformation create-stack --disable-rollback --stack-name steveVM --template-body file://vpc.json --parameters ParameterKey=KeyPair,ParameterValue=steveshilling ParameterKey=subnetAZ,ParameterValue=eu-central-1b ParameterKey=Region,ParameterValue=eu-central-1 --capabilities CAPABILITY_IAM

