#!/bin/bash

regions="us-east-1
us-east-2
us-west-1
us-west-2
ap-south-1
ap-northeast-1
ap-northeast-2
ap-northeast-3
ap-southeast-1
ap-southeast-2
ca-central-1
cn-north-1
cn-northwest-1
eu-central-1
eu-west-1
eu-west-2
eu-west-3
sa-east-1"

for region in $regions
do
	functions=$(aws lambda list-functions --region $region 2>/dev/null | jq -r '.Functions[].FunctionName' 2>/dev/null)
	#if (( $(echo "$functions" | wc -c) > 0 ))
	if echo "$functions" | grep -v '^$' >/dev/null 2>&1
        then
		echo "${region}: "
		echo "$functions" | sed 's/^/\t/'
	fi
done
