#!/bin/bash

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	functions=$(aws lambda list-functions --region $region 2>/dev/null | jq -r '.Functions[].FunctionName' 2>/dev/null)
	#if (( $(echo "$functions" | wc -c) > 0 ))
	if echo "$functions" | grep -v '^$' >/dev/null 2>&1
        then
		echo "${region}: "
		echo "$functions" | sed 's/^/\t/'
	fi
done
