#!/bin/bash

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "$region:"
	aws apigateway get-rest-apis --region $region | jq -r '.items[] | .name+","+ .id' | sed 's/^/\t/'
done

