#!/bin/bash

if (( $# < 1 ))
then
	echo "Syntax is: $0 <region>" 1>&2
	exit 1
fi

# Gets all info about stopped containers
aws ec2 describe-instances --region $1 | jq '.Reservations[].Instances[] | select(.State.Name == "stopped") | [.InstanceId,.State.Name,.Tags[].Value]'
