#!/bin/bash

if (( $# < 1 ))
then
	echo "SYNTAX: $0 ownerID" 1>&2
	exit 1
fi

ownerid=$1

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "AMIs in $region"

	aws ec2 describe-snapshots --owner ${ownerid} --region $region | jq '.Snapshots[] | [.SnapshotId,.Description,.VolumeId]'

done
