#!/bin/bash

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "RDS in $region"
	aws rds describe-db-instances --region $region | jq '.DBInstances[] | [ "Class: "+.DBInstanceClass,"Engine: "+.Engine,"Size: "+(.AllocatedStorage|tostring),.DBInstanceIdentifier,.InstanceCreateTime]'
done
