#!/bin/bash

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "EIPs in $region:"
	aws ec2 describe-addresses --region $region | jq '.Addresses[] | {"Allocation": .AllocationId, "Instance": .InstanceId, "Public IP": .PublicIp, "Private IP": .PrivateIpAddress}' | sed 's/^/\t/'
done
