#!/bin/bash

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "VPCs in $region"
	aws ec2 describe-vpcs --region $region | jq '.Vpcs[] | [ "VPC ID: "+.VpcId, .Tags[].Key+": "+.Tags[].Value]' 2>/dev/null
done
