#!/bin/bash

if (( $# < 1 ))
then
        echo "SYNTAX: $0 ownerID" 1>&2
        exit 1
fi

ownerid=$1

for region in $(aws ec2 describe-regions | jq -r '.Regions[] | .RegionName')
do
	echo "AMIs in $region"
	aws ec2 describe-images --owner ${ownerid} --region $region | jq '.Images[] | ["ID: "+.ImageId,"Name: "+.Name,"Creation: "+.CreationDate,"VirtType: "+.VirtualizationType,"Description: "+.Description,"Snapshot: "+.BlockDeviceMappings[].Ebs.SnapshotId]'
done
